name: Feature Request
description: Propose a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please explain the problem you are solving and how the proposed change helps.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a specific problem or limitation?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
